// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"97e289697ca5b4b50095a9f701f8e6272140b4a99a2785a1312792e32064a28a32a6753b869aa4846b677508cb5598026f138f4fe2cfc1e7787c1d72efc374ab"}}
];
